### ISSUE TITLE
Total Profi % calculation incorrect

### ISSUE THREAD

**Issue by ninjaWhippet** [AtsutaneDotNet/Crypto-Tracker#1]
I've realised the Total Profit % is being calculated wrong.
I think there's an error with the way it comes up with total profit, in the db it just adds the current daily % profit ("daily") to yesterdays "overall" profit %. Adding individual days profit % this way doesn't work mathematically, it should be using "today" ($) / starting account balance ($) as a percentage to calculate the running account increase.

![Crypto Tracker Total Profit Percentage error 1](https://user-images.githubusercontent.com/74751771/104900540-46279180-59d0-11eb-94cf-d6f5b6f60cb3.JPG)

![Crypto Tracker Total Profit Percentage error 2](https://user-images.githubusercontent.com/74751771/104900571-4de73600-59d0-11eb-8322-41dccf8dc895.JPG)

**Comment by AtsutaneDotNet** [comment]
Fix in [#d1f3d62](https://github.com/AtsutaneDotNet/Crypto-Tracker/commit/d1f3d6239598ab36d27444db49d0b855ca076afc)
