### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'float' and 'tuple'

### ISSUE THREAD

**Issue by goneale** [AtsutaneDotNet/Crypto-Tracker#2]
After about a week of running the tracker. 
![image](https://user-images.githubusercontent.com/107109/106371892-c0cfb400-63b5-11eb-8bd6-7be915f2ec4e.png)

4 accounts
![image](https://user-images.githubusercontent.com/107109/106371905-f4124300-63b5-11eb-9dd9-de2c9ab0c2da.png)

**Comment by AtsutaneDotNet** [comment]
Can't seem to recreate this issue. Try renaming tracker.db file and run back the main.py.
